/** @type {import('@dshapps/app-check').AppCheckConfig} */
export default {
  name: '@dshapps/usage-app',
  expectedClientInject: [
    '@dshapps/webpage',
    '@deepseek-ai/dsh-client-locale',
    '@deepseek-ai/dsh-client-runtime',
    '@deepseek-ai/dsh-client-ui-conversation',
  ],
  packedAllowlist: [
    'package/package.json',
    'package/README.md',
    'package/README.zh.md',
    'package/LICENSE',
    'package/NOTICE',
    'package/cordis.patch.yml',
    'package/lib/index.js',
    'package/lib/invariant.js',
    'package/lib/client.js',
    'package/lib/client.js.map',
    'package/lib/types/index.d.ts',
    'package/lib/types/invariant.d.ts',
    'package/lib/types/fold.d.ts',
    'package/lib/types/balances.d.ts',
    'package/lib/types/subscriptions.d.ts',
    'package/lib/types/collect.d.ts',
    'package/lib/types/http.d.ts',
    'package/lib/types/client/index.d.ts',
    'package/lib/types/client/locales.d.ts',
    'package/lib/types/client/usage-view.d.ts',
    'package/lib/types/client/UsageApp.d.ts',
    'package/lib/types/client/UsageAccountPane.d.ts',
    'package/lib/types/client/UsagePeriodHero.d.ts',
    'package/lib/types/client/UsageHeaderAction.d.ts',
  ],
  patchMustInclude: ["name: '@dshapps/usage-app'"],
  patchMustNotInclude: ["name: '@dshapps/webpage'"],
  allowFileDshPins: true,
  require: {
    publishable: true,
    packageManager: true,
    enginesNode: true,
    clientPlatformWeb: true,
    webpagePeer: true,
    noWorkspaceRanges: true,
    noAdjacentCheckout: true,
    noForbiddenUi: true,
    localeZhEn: true,
    invariantExport: true,
    clientExport: true,
    noNodeDefaultExport: true,
    clientCssInjection: true,
    singleTarball: true,
    noPrepare: true,
  },
}
